// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1b7IrV3gVPa6qeW-M4XfLQ4tXr4hfDM',
    appId: '1:63922719967:web:2f64a2ad08e89abd61ed6a',
    messagingSenderId: '63922719967',
    projectId: 'ict602-fce3e',
    authDomain: 'ict602-fce3e.firebaseapp.com',
    storageBucket: 'ict602-fce3e.firebasestorage.app',
    measurementId: 'G-6W5GG6CR9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxC-_dHPctquQoo9Eh1UVbYOArqGFjts',
    appId: '1:63922719967:android:c19617f9ca53053261ed6a',
    messagingSenderId: '63922719967',
    projectId: 'ict602-fce3e',
    storageBucket: 'ict602-fce3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquY7aWSpbeRc5ORBQ-UW0mEaW1xXp_EA',
    appId: '1:63922719967:ios:83bfcb1d9a7bba8c61ed6a',
    messagingSenderId: '63922719967',
    projectId: 'ict602-fce3e',
    storageBucket: 'ict602-fce3e.firebasestorage.app',
    iosClientId: '63922719967-lbebdabs9rjddtip58feukvkakvj2g31.apps.googleusercontent.com',
    iosBundleId: 'com.example.ict602Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquY7aWSpbeRc5ORBQ-UW0mEaW1xXp_EA',
    appId: '1:63922719967:ios:83bfcb1d9a7bba8c61ed6a',
    messagingSenderId: '63922719967',
    projectId: 'ict602-fce3e',
    storageBucket: 'ict602-fce3e.firebasestorage.app',
    iosClientId: '63922719967-lbebdabs9rjddtip58feukvkakvj2g31.apps.googleusercontent.com',
    iosBundleId: 'com.example.ict602Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1b7IrV3gVPa6qeW-M4XfLQ4tXr4hfDM',
    appId: '1:63922719967:web:3affed3be90d8c6d61ed6a',
    messagingSenderId: '63922719967',
    projectId: 'ict602-fce3e',
    authDomain: 'ict602-fce3e.firebaseapp.com',
    storageBucket: 'ict602-fce3e.firebasestorage.app',
    measurementId: 'G-XYQMED52RN',
  );
}
